language: java

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew build --debug

  openssl aes-256-cbc -K $encrypted_2b51ae3bcf84_key -iv $encrypted_2b51ae3bcf84_iv -in credentials.properties.enc -out credentials.properties -d

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  - codecov
