language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
  - chmod +x ./config/scripts/publish-artifacts.sh
  # Decrypt and unarchive Maven credentials.
  - openssl aes-256-cbc -K $encrypted_4ded43a06dc3_key -iv $encrypted_4ded43a06dc3_iv -in cloudrepo.properties.enc -out cloudrepo.properties -d


script:
  - ./gradlew build --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
