language: java

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew build --debug

  # Decrypt and unarchive Maven credentials.
  - openssl aes-256-cbc -K $encrypted_0d67f1266b19_key -iv $encrypted_0d67f1266b19_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  - codecov
