language: java

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew build --debug

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  - codecov
