name: Build under Ubuntu

on:
  pull_request:
    branches:
      - master
      - 1.x-dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      # todo: This is a tempopary step. Remove it once the issue is solved.
      - name: Analyze the dependency conflict
        shell: bash
        run: ./gradlew :rdbms:dependencyInsight --configuration testCompileClasspath --dependency io.spine:spine-testlib

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build
